#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-curry
Version  : 2.000001
Release  : 24
URL      : https://cpan.metacpan.org/authors/id/M/MS/MSTROUT/curry-2.000001.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MS/MSTROUT/curry-2.000001.tar.gz
Summary  : 'Create automatic curried method call closures for any class or object'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-1.0
Requires: perl-curry-license = %{version}-%{release}
Requires: perl-curry-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
NAME
curry - Create automatic curried method call closures for any class or
object

%package dev
Summary: dev components for the perl-curry package.
Group: Development
Provides: perl-curry-devel = %{version}-%{release}
Requires: perl-curry = %{version}-%{release}

%description dev
dev components for the perl-curry package.


%package license
Summary: license components for the perl-curry package.
Group: Default

%description license
license components for the perl-curry package.


%package perl
Summary: perl components for the perl-curry package.
Group: Default
Requires: perl-curry = %{version}-%{release}

%description perl
perl components for the perl-curry package.


%prep
%setup -q -n curry-2.000001
cd %{_builddir}/curry-2.000001

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-curry
cp %{_builddir}/curry-2.000001/LICENSE %{buildroot}/usr/share/package-licenses/perl-curry/97610ce5c93c5cf56e7f26bed6f380459e25b922
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/curry.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-curry/97610ce5c93c5cf56e7f26bed6f380459e25b922

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
